### ISSUE TITLE
There are two aliases for USB ID 0bda:8812 in 4.3.14, 4.3.20 and 4.3.22

### ISSUE THREAD

**Issue by MrEngman** [diederikdehaas/rtl8812AU#38]
Just downloaded and compiled the code for raspbian 4.4.23-v7+ and noticed there are two entries in the list of aliases for USB ID 0bda:8812 in the compiled module.

This is caused by the addition of the line defining the entry for the Alfa AWUS036AC in os_dep/linux/usb_intf.c

The line

`{USB_DEVICE(USB_VENDER_ID_REALTEK, 0x8812),.driver_info = RTL8812},/* Default ID */`

creates USB ID 0bda:8812 by default, and the line 

`{USB_DEVICE(0x0BDA, 0x8812),.driver_info = RTL8812}, /* Alfa - AWUS036AC */`

creates a second copy of USB ID 0bda:8812

So adding the entry for the Alfa AWUS036AC is not necessary as the USB ID it uses is already defined.

This occurs in the code for 4.3.14 (lines 278/291), 4.3.20 (lines 145/158) and 4.3.22 (lines 145/158)

**Comment by diederikdehaas** [comment]
Thanks for the report @MrEngman :+1: 

I have applied the changes to all branches of which only the 'official' 4.3.20 branch is local only, but I did update the _wip_ variant here on GitHub.
