### ISSUE TITLE
Need Help! 8812au v4.3.14 to mips

### ISSUE THREAD

**Issue by DelBierzo** [diederikdehaas/rtl8812AU#42]
i need the 8812au v4.3.14 to mips for a "Gigablue tv box", I have no linux idea.
I install ubuntu 16.10 to try, but I am not able to prepare the cross compile.
Could someone please compile. 

The Kernel version its: 3.14.2
lsusb: 0bda:0811

Thank you

**Comment by DelBierzo** [comment]
Solved by installing a newer image decoder. (OpenATV 5.3)

**Comment by diederikdehaas** [comment]
I was hoping that someone would come up with a procedure to cross-compile for MIPS. Ah well, maybe some still does :smile:
