### ISSUE TITLE
openwrt/LEDE wireless compat

### ISSUE THREAD

**Issue by lucize** [diederikdehaas/rtl8812AU#57]
building against wireless compat gives this error when I try to insmod the module

 8812au: Unknown symbol __ieee80211_get_channel (err 0)

Regards

**Comment by atyg02** [comment]
First manually copy compat-wireless "Module.symvers" located in build_dir/target.../linux-.../compat-wireless into the folder "staging_dir/target.../usr/include/mac80211/Module.symvers" as to allow proper linking.

You can get the patches and the Makefile from here: https://github.com/dl12345/rtl8812au

**Comment by lucize** [comment]
many thanks !
is working

regards
