### ISSUE TITLE
How to install 

### ISSUE THREAD

**Issue by jjcantu** [diederikdehaas/rtl8812AU#66]
I am fairly new at Linux I am barely learning how all this works. I need help connecting to the internet as most hacks require you connect to the wifi, so if someone doesn't mind can someone show me how to install this driver onto Linux so i can connect to the internet wirelessly

**Comment by ladsoftware** [comment]
i'm running ubuntu 17.04
amd 8350
amd r9 290


I use this inside the folder in the terminal:
sudo make
sudo make install

**Comment by myh1234567** [comment]
it showes fatal error: stdarg.h: no such file 

what should i do 
im running on ubuntu 18.04
