### ISSUE TITLE
Build error on latest RasPi kernel

### ISSUE THREAD

**Issue by austinmarkus** [diederikdehaas/rtl8812AU#70]
Hi,

I'm getting a build error on the Raspbian 4.9.24-v7+ kernel. I've tried both the 4.3.14-9 and 4.3.22-beta-6 releases with the same errors. Log from build is below. Thanks for any help, as it used to work wonderfully prior to the latest update.

-Austin

----

  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/core/rtw_ioctl_set.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/core/rtw_ieee80211.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/core/rtw_mlme.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/core/rtw_mlme_ext.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/core/rtw_wlan_util.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/core/rtw_vht.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/core/rtw_pwrctrl.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/core/rtw_rf.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/core/rtw_recv.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/core/rtw_sta_mgt.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/core/rtw_ap.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/core/rtw_xmit.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/core/rtw_p2p.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/core/rtw_tdls.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/core/rtw_br_ext.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/core/rtw_iol.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/core/rtw_sreset.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/core/rtw_btcoex.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/core/rtw_beamforming.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/core/rtw_odm.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/core/efuse/rtw_efuse.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/osdep_service.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/os_intfs.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/usb_intf.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/usb_ops_linux.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_linux.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/xmit_linux.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/mlme_linux.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/recv_linux.o
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.o
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:92:12: error: ‘IEEE80211_BAND_2GHZ’ undeclared here (not in a function)
  .band   = IEEE80211_BAND_2GHZ,  \
            ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:150:2: note: in expansion of macro ‘CHAN2G’
  CHAN2G(1, 2412, 0),
  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:101:12: error: ‘IEEE80211_BAND_5GHZ’ undeclared here (not in a function)
  .band   = IEEE80211_BAND_5GHZ,  \
            ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:167:2: note: in expansion of macro ‘CHAN5G’
  CHAN5G(34, 0),  CHAN5G(36, 0),
  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:167:2: error: initializer element is not constant
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:167:2: error: (near initialization for ‘rtw_5ghz_a_channels[0].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:167:2: error: initializer element is not constant
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:167:2: error: (near initialization for ‘rtw_5ghz_a_channels[1].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:168:2: error: initializer element is not constant
  CHAN5G(38, 0),  CHAN5G(40, 0),
  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:168:2: error: (near initialization for ‘rtw_5ghz_a_channels[2].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:168:2: error: initializer element is not constant
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:168:2: error: (near initialization for ‘rtw_5ghz_a_channels[3].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:169:2: error: initializer element is not constant
  CHAN5G(42, 0),  CHAN5G(44, 0),
  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:169:2: error: (near initialization for ‘rtw_5ghz_a_channels[4].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:169:2: error: initializer element is not constant
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:169:2: error: (near initialization for ‘rtw_5ghz_a_channels[5].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:170:2: error: initializer element is not constant
  CHAN5G(46, 0),  CHAN5G(48, 0),
  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:170:2: error: (near initialization for ‘rtw_5ghz_a_channels[6].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:170:2: error: initializer element is not constant
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:170:2: error: (near initialization for ‘rtw_5ghz_a_channels[7].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:171:2: error: initializer element is not constant
  CHAN5G(52, 0),  CHAN5G(56, 0),
  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:171:2: error: (near initialization for ‘rtw_5ghz_a_channels[8].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:171:2: error: initializer element is not constant
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:171:2: error: (near initialization for ‘rtw_5ghz_a_channels[9].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:172:2: error: initializer element is not constant
  CHAN5G(60, 0),  CHAN5G(64, 0),
  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:172:2: error: (near initialization for ‘rtw_5ghz_a_channels[10].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:172:2: error: initializer element is not constant
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:172:2: error: (near initialization for ‘rtw_5ghz_a_channels[11].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:173:2: error: initializer element is not constant
  CHAN5G(100, 0),  CHAN5G(104, 0),
  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:173:2: error: (near initialization for ‘rtw_5ghz_a_channels[12].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:173:2: error: initializer element is not constant
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:173:2: error: (near initialization for ‘rtw_5ghz_a_channels[13].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:174:2: error: initializer element is not constant
  CHAN5G(108, 0),  CHAN5G(112, 0),
  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:174:2: error: (near initialization for ‘rtw_5ghz_a_channels[14].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:174:2: error: initializer element is not constant
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:174:2: error: (near initialization for ‘rtw_5ghz_a_channels[15].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:175:2: error: initializer element is not constant
  CHAN5G(116, 0),  CHAN5G(120, 0),
  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:175:2: error: (near initialization for ‘rtw_5ghz_a_channels[16].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:175:2: error: initializer element is not constant
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:175:2: error: (near initialization for ‘rtw_5ghz_a_channels[17].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:176:2: error: initializer element is not constant
  CHAN5G(124, 0),  CHAN5G(128, 0),
  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:176:2: error: (near initialization for ‘rtw_5ghz_a_channels[18].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:176:2: error: initializer element is not constant
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:176:2: error: (near initialization for ‘rtw_5ghz_a_channels[19].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:177:2: error: initializer element is not constant
  CHAN5G(132, 0),  CHAN5G(136, 0),
  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:177:2: error: (near initialization for ‘rtw_5ghz_a_channels[20].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:177:2: error: initializer element is not constant
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:177:2: error: (near initialization for ‘rtw_5ghz_a_channels[21].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:178:2: error: initializer element is not constant
  CHAN5G(140, 0),  CHAN5G(149, 0),
  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:178:2: error: (near initialization for ‘rtw_5ghz_a_channels[22].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:178:2: error: initializer element is not constant
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:178:2: error: (near initialization for ‘rtw_5ghz_a_channels[23].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:179:2: error: initializer element is not constant
  CHAN5G(153, 0),  CHAN5G(157, 0),
  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:179:2: error: (near initialization for ‘rtw_5ghz_a_channels[24].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:179:2: error: initializer element is not constant
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:179:2: error: (near initialization for ‘rtw_5ghz_a_channels[25].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:180:2: error: initializer element is not constant
  CHAN5G(161, 0),  CHAN5G(165, 0),
  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:180:2: error: (near initialization for ‘rtw_5ghz_a_channels[26].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:180:2: error: initializer element is not constant
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:180:2: error: (near initialization for ‘rtw_5ghz_a_channels[27].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:181:2: error: initializer element is not constant
  CHAN5G(184, 0),  CHAN5G(188, 0),
  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:181:2: error: (near initialization for ‘rtw_5ghz_a_channels[28].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:181:2: error: initializer element is not constant
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:181:2: error: (near initialization for ‘rtw_5ghz_a_channels[29].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:182:2: error: initializer element is not constant
  CHAN5G(192, 0),  CHAN5G(196, 0),
  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:182:2: error: (near initialization for ‘rtw_5ghz_a_channels[30].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:182:2: error: initializer element is not constant
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:182:2: error: (near initialization for ‘rtw_5ghz_a_channels[31].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:183:2: error: initializer element is not constant
  CHAN5G(200, 0),  CHAN5G(204, 0),
  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:183:2: error: (near initialization for ‘rtw_5ghz_a_channels[32].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:183:2: error: initializer element is not constant
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:183:2: error: (near initialization for ‘rtw_5ghz_a_channels[33].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:184:2: error: initializer element is not constant
  CHAN5G(208, 0),  CHAN5G(212, 0),
  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:184:2: error: (near initialization for ‘rtw_5ghz_a_channels[34].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:184:2: error: initializer element is not constant
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:184:2: error: (near initialization for ‘rtw_5ghz_a_channels[35].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:185:2: error: initializer element is not constant
  CHAN5G(216, 0),
  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:185:2: error: (near initialization for ‘rtw_5ghz_a_channels[36].band’)
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:219:2: warning: ‘enum ieee80211_band’ declared inside parameter list
  )
  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:219:2: warning: its scope is only this definition or declaration, which is probably not what you want
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:218:22: error: parameter 1 (‘band’) has incomplete type
  enum ieee80211_band band
                      ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:217:34: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
 struct ieee80211_supported_band *rtw_spt_band_alloc(
                                  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_spt_band_alloc’:
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:249:17: error: incompatible types when assigning to type ‘enum nl80211_band’ from type ‘struct ieee80211_channel *’
  spt_band->band = band;
                 ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_spt_band_free’:
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:278:20: warning: comparison between pointer and integer
  if(spt_band->band == IEEE80211_BAND_2GHZ)
                    ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:284:25: warning: comparison between pointer and integer
  else if(spt_band->band == IEEE80211_BAND_5GHZ)
                         ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_cfg80211_indicate_scan_done’:
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:2030:4: error: incompatible type for argument 2 of ‘cfg80211_scan_done’
    cfg80211_scan_done(pwdev_priv->scan_request, aborted);
    ^
In file included from /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/include/osdep_service_linux.h:87:0,
                 from /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/include/osdep_service.h:41,
                 from /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:22:
./include/net/cfg80211.h:4304:6: note: expected ‘struct cfg80211_scan_info *’ but argument is of type ‘bool’
 void cfg80211_scan_done(struct cfg80211_scan_request *request,
      ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c: At top level:
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:6191:105: warning: ‘enum ieee80211_band’ declared inside parameter list
 static void rtw_cfg80211_init_ht_capab_ex(_adapter *padapter, struct ieee80211_sta_ht_cap *ht_cap, enum ieee80211_band band, u8 rf_type)
                                                                                                         ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:6191:120: error: parameter 3 (‘band’) has incomplete type
 static void rtw_cfg80211_init_ht_capab_ex(_adapter *padapter, struct ieee80211_sta_ht_cap *ht_cap, enum ieee80211_band band, u8 rf_type)
                                                                                                                        ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:6191:13: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
 static void rtw_cfg80211_init_ht_capab_ex(_adapter *padapter, struct ieee80211_sta_ht_cap *ht_cap, enum ieee80211_band band, u8 rf_type)
             ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:6239:102: warning: ‘enum ieee80211_band’ declared inside parameter list
 static void rtw_cfg80211_init_ht_capab(_adapter *padapter, struct ieee80211_sta_ht_cap *ht_cap, enum ieee80211_band band, u8 rf_type)
                                                                                                      ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:6239:117: error: parameter 3 (‘band’) has incomplete type
 static void rtw_cfg80211_init_ht_capab(_adapter *padapter, struct ieee80211_sta_ht_cap *ht_cap, enum ieee80211_band band, u8 rf_type)
                                                                                                                     ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:6239:13: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
 static void rtw_cfg80211_init_ht_capab(_adapter *padapter, struct ieee80211_sta_ht_cap *ht_cap, enum ieee80211_band band, u8 rf_type)
             ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_cfg80211_init_wiphy’:
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:6307:23: error: array subscript is not an integer
   bands = wiphy->bands[IEEE80211_BAND_2GHZ];
                       ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:6307:9: warning: assignment from incompatible pointer type
   bands = wiphy->bands[IEEE80211_BAND_2GHZ];
         ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:6313:23: error: array subscript is not an integer
   bands = wiphy->bands[IEEE80211_BAND_5GHZ];
                       ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:6313:9: warning: assignment from incompatible pointer type
   bands = wiphy->bands[IEEE80211_BAND_5GHZ];
         ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_cfg80211_preinit_wiphy’:
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:6403:15: error: array subscript is not an integer
   wiphy->bands[IEEE80211_BAND_2GHZ] = rtw_spt_band_alloc(IEEE80211_BAND_2GHZ);
               ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:6407:15: error: array subscript is not an integer
   wiphy->bands[IEEE80211_BAND_5GHZ] = rtw_spt_band_alloc(IEEE80211_BAND_5GHZ);
               ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_wiphy_free’:
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:6555:18: error: array subscript is not an integer
  if (wiphy->bands[IEEE80211_BAND_2GHZ]) {
                  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:6556:33: error: array subscript is not an integer
   rtw_spt_band_free(wiphy->bands[IEEE80211_BAND_2GHZ]);
                                 ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:6556:21: warning: passing argument 1 of ‘rtw_spt_band_free’ from incompatible pointer type
   rtw_spt_band_free(wiphy->bands[IEEE80211_BAND_2GHZ]);
                     ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:271:6: note: expected ‘struct ieee80211_supported_band *’ but argument is of type ‘struct ieee80211_channel *’
 void rtw_spt_band_free(struct ieee80211_supported_band *spt_band)
      ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:6557:15: error: array subscript is not an integer
   wiphy->bands[IEEE80211_BAND_2GHZ] = NULL;
               ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:6559:18: error: array subscript is not an integer
  if (wiphy->bands[IEEE80211_BAND_5GHZ]) {
                  ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:6560:33: error: array subscript is not an integer
   rtw_spt_band_free(wiphy->bands[IEEE80211_BAND_5GHZ]);
                                 ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:6560:21: warning: passing argument 1 of ‘rtw_spt_band_free’ from incompatible pointer type
   rtw_spt_band_free(wiphy->bands[IEEE80211_BAND_5GHZ]);
                     ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:271:6: note: expected ‘struct ieee80211_supported_band *’ but argument is of type ‘struct ieee80211_channel *’
 void rtw_spt_band_free(struct ieee80211_supported_band *spt_band)
      ^
/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.c:6561:15: error: array subscript is not an integer
   wiphy->bands[IEEE80211_BAND_5GHZ] = NULL;
               ^
cc1: some warnings being treated as errors
scripts/Makefile.build:293: recipe for target '/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.o' failed
make[2]: *** [/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build/os_dep/linux/ioctl_cfg80211.o] Error 1
Makefile:1490: recipe for target '_module_/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build' failed
make[1]: *** [_module_/var/lib/dkms/rtl8812AU/4.3.22-beta-6/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.9.24-v7+'
Makefile:1693: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by MrEngman** [comment]
Not sure what 4.3.14-9 and 4.3.22-beta-6 refer to. I clone the source and checkout either driver-4.3.14 or driver-4.3.22-beta. So not sure what the -9 and -6 reference.

It compiles OK for me. I do get a couple of warnings but the compile finishes OK, however, I cross-compile on a PC.

The error referencing IEEE80211_BAND_2GHZ and IEEE80211_BAND_5GHZ would suggest to me your source code is not up to date. Check file `include/rtw_wifi_regd.h` and see if it includes
```#if (LINUX_VERSION_CODE >= KERNEL_VERSION(4, 7, 0))
#define ieee80211_band nl80211_band
#define IEEE80211_BAND_2GHZ NL80211_BAND_2GHZ
#define IEEE80211_BAND_5GHZ NL80211_BAND_5GHZ
#define IEEE80211_NUM_BANDS NUM_NL80211_BANDS
#endif
```
If not your code needs updating.

**Comment by austinmarkus** [comment]
Thank you for your quick response, I was using your release tarballs and not a git clone. Updating to the latest clone solved the issue. You might want to consider updating your releases to reflect the changes.

Thanks again,

Austin
