### ISSUE TITLE
Tp-link ac1300 Archer T4U

### ISSUE THREAD

**Issue by iomavridis** [diederikdehaas/rtl8812AU#91]
I have already installed the driver 4.3.22-beta and it's run perfect with D-link dwa-171 and Edimax Ew-7811utc, but unfortunately, it just isn't working  for my new  adapter Tplink Archer ac1300.

**Comment by diederikdehaas** [comment]
What is the Bus ID (`lsusb`)?

**Comment by iomavridis** [comment]
I found a solution [here](https://unix.stackexchange.com/questions/345375/issue-while-installing-driver-for-archer-t4u-ac1300-on-mint-17) that works for me. 
Update /rtl8812au/os_dep/linux/usb_intf.c-> find the original bus id for the archer T4U AC1200 (2357:0101) and add a line with the bus id for the AC1300 (2357:010d) right after:

{USB_DEVICE(0x2357, 0x0101),.driver_info = RTL8812},    
**{USB_DEVICE(0x2357, 0x010d),.driver_info = RTL8812},**

**Comment by diederikdehaas** [comment]
That was why I wanted to know the ID (so it is `2357:010d`) ;-)
