### ISSUE TITLE
DKMS recommended steps fail, no git archive found?

### ISSUE THREAD

**Issue by dachshund-digital** [diederikdehaas/rtl8812AU#95]
****DKMS recommended steps fail, no git archive found?
This step fails...

# git archive driver-${DRV_VERSION} | tar -x -C /usr/src/${DRV_NAME}-${DRV_VERSION}****

**Comment by Allendar** [comment]
Either be in `root` mode or run the second command, as described on the README as root:

```
git archive driver-${DRV_VERSION} | sudo tar -x -C /usr/src/${DRV_NAME}-${DRV_VERSION}****
```

**Comment by dachshund-digital** [comment]
Right, I was root at the time.  It was the git archive pull that was falling, which as odd.  Tar never got file to process.  I tried it again yesterday evening and it worked as expected.
